POST http://localhost:7777/events
Content-Type: application/json

{
    "title":69,
    "details":"Evento de + experiência para programadores!",
    "maximumAttendees":1
    
    }

###

POST http://localhost:7777/events/devops-summit/attendees
Content-Type: application/json

{
    "name": "Lilevo  Nagarupa",
    "email":"nagarupa.lilevo@portoweb.com.br"
}


### - Get event 

GET http://127.0.0.1:7777/events/devss-summit
Content-Type: application/json

### - BADGE

GET http://localhost:7777/attendees/12/badge
Content-Type: text/plain


### - CheckIn

GET http://127.0.0.1:7777/attendees/11/checkin
Content-Type: text/plain


### - Get EVENT ATTENDEES

GET http://127.0.0.1:7777/events/devops-summit/attendees
Content-Type: application/json