POST http://localhost:7777/events
Content-Type: application/json

{
    "title":69,
    "details":"Evento de + experiência para programadores!",
    "maximumAttendees":1
    
    }

### Register attendee

POST http://localhost:3001/events/js-brasil-2024/attendees
Content-Type: application/json

{
    "name": "Ben Dover",
    "email":"benD@portoweb.com.br"
}


### - Get event 

GET http://127.0.0.1:3001/events/devops-summit
Content-Type: application/json

### - BADGE

GET http://localhost:3001/attendees/clv66fghw0001qoq5untatl9x/badge
Content-Type: text/plain


### - CheckIn

GET http://127.0.0.1:7777/attendees/clv1p9o330001w8i1vyqbt48m/checkin
Content-Type: text/plain


### - Get EVENT ATTENDEES

GET http://127.0.0.1:3001/events/js-brasil-2024/attendees?
Content-Type: application/json