version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-event-pass
    ports: 
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - eventpass

  api-event-pass:
    build:
      context: .
    container_name: api-event-pass
    ports:
      - 3001:7777
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - API_BASE_URL=http://localhost:7777
    depends_on:
      - postgres
    networks:
      - eventpass  
networks:
  eventpass:
    driver: bridge

volumes:
  db:
